/*
 *  "sym_SECOND.java"
 *	Esta clase representa la tabla de símbolos que utiliza el segundo parser (parser_SECOND).
 *	El siguiente código ha sido generado automáticamente con <CUP v0.10k> 
 * 
 *
 *  Copyright (C) 2005, 2006 Jose Manuel Martínez García <glasnosh@gmail.com>
 *
 *  This program is "Open Source" software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License (explicitly version 2 
 *   of the License).
 */
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Nov 15 23:54:35 CET 2005
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym_SECOND {
  /* terminals */
  public static final int P_D = 10;
  public static final int MASGRANDE = 23;
  public static final int ARRIBA = 32;
  public static final int ESFERA = 20;
  public static final int MISMOCOLOR = 26;
  public static final int IZQUIERDA = 30;
  public static final int PIRAMIDE = 22;
  public static final int IMPLICA = 5;
  public static final int MISMAFORMA = 25;
  public static final int CUBO = 21;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int OR = 3;
  public static final int BIMPLICA = 8;
  public static final int SEPARATOR = 11;
  public static final int MASPEQUENHO = 24;
  public static final int MISMAFILA = 28;
  public static final int MISMACOLUMNA = 29;
  public static final int EOF = 0;
  public static final int EQUAL = 6;
  public static final int error = 1;
  public static final int ROJO = 17;
  public static final int DIGITO = 7;
  public static final int MISMOTAMANHO = 27;
  public static final int TAUTO = 13;
  public static final int ALREDEDOR = 34;
  public static final int ERROR = 12;
  public static final int AZUL = 18;
  public static final int DERECHA = 31;
  public static final int ABAJO = 33;
  public static final int FALSE = 14;
  public static final int AMARILLO = 19;
  public static final int GRANDE = 15;
  public static final int ENTRE = 35;
  public static final int PEQUENHO = 16;
  public static final int P_I = 9;
}

