/*
 *  "sym_STATUS.java"
 *	Esta clase representa la tabla de símbolos que utiliza "parser_STATUS"..
 *	El siguiente código ha sido generado automáticamente con <CUP v0.10k> 
 * 
 *
 *  Copyright (C) 2005, 2006 Jose Manuel Martínez García <glasnosh@gmail.com>
 *
 *  This program is "Open Source" software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License (explicitly version 2 
 *   of the License).
 */
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 18 12:09:03 CET 2006
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym_STATUS {
  /* terminals */
  public static final int P_D = 12;
  public static final int MASGRANDE = 27;
  public static final int ARRIBA = 36;
  public static final int NOMBRE = 8;
  public static final int ESFERA = 24;
  public static final int MISMOCOLOR = 30;
  public static final int IZQUIERDA = 34;
  public static final int PIRAMIDE = 26;
  public static final int IMPLICA = 6;
  public static final int CU = 13;
  public static final int MISMAFORMA = 29;
  public static final int CUBO = 25;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int OR = 3;
  public static final int BIMPLICA = 10;
  public static final int SEPARATOR = 15;
  public static final int CE = 14;
  public static final int MASPEQUENHO = 28;
  public static final int MISMAFILA = 32;
  public static final int MISMACOLUMNA = 33;
  public static final int EOF = 0;
  public static final int EQUAL = 7;
  public static final int error = 1;
  public static final int ROJO = 21;
  public static final int MISMOTAMANHO = 31;
  public static final int TAUTO = 17;
  public static final int ALREDEDOR = 38;
  public static final int ERROR = 16;
  public static final int NOT_C = 5;
  public static final int AZUL = 22;
  public static final int DERECHA = 35;
  public static final int VARIABLE = 9;
  public static final int ABAJO = 37;
  public static final int FALSE = 18;
  public static final int AMARILLO = 23;
  public static final int GRANDE = 19;
  public static final int ENTRE = 39;
  public static final int PEQUENHO = 20;
  public static final int P_I = 11;
}

